### ISSUE TITLE
Add contribution guide

### ISSUE THREAD

**Issue by mazipan** [mazipan/awesome-vue-list#6]
I need contribution guide in this repo.
You can see the sample contribution guide from this pull request
https://github.com/mazipan/vue-currency-filter/pull/5/files

Thanks for your help 🎉🎉🎉

**Comment by ahaggard2013** [comment]
Looking for the same format with the names changed?  I'll do it real quick.

**Comment by abhanshgiri21** [comment]
is someone working on this or i can take it?
